[build]
  command = "node build.js"
  publish = "public/Public/public/Public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Auto-clear staff every 30 minutes
[[scheduled_functions]]
  name = "auto-clear-staff"
  cron = "*/30 * * * *"

# Resend unconfirmed broadcasts every 1 minute
[[scheduled_functions]]
  name = "resend-broadcast"
  cron = "* * * * *"

# Weather monitor every 10 minutes
[[scheduled_functions]]
  name = "weather-monitor"
  cron = "*/10 * * * *"

# Send scheduled messages every 5 minutes
[[scheduled_functions]]
  name = "send-scheduled"
  cron = "*/5 * * * *"
